/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.4
 * Generated at: 2025-03-17 11:25:11 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.List;
import java.util.HashMap;
import java.util.ArrayList;
import java.util.Arrays;

public final class plan_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(6);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("java.util.Arrays");
    _jspx_imports_classes.add("java.util.HashMap");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    ");

        HashMap<String, List<List<String>>> plan = (HashMap<String, List<List<String>>>) request.getAttribute("Plan");
        List<String> keys = new ArrayList<>(plan.keySet());
        String date= "Today";
        for (String n: keys) {
            if (n.equals("Tomorrow") || n.equals("Today") || n.equals("Yesterday")) {
                date = n;
            }
        }
        List<String> sortedKeys = new ArrayList<>(Arrays.asList("MORNING", "AFTERNOON", "EVENING"));
    
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <title>");
      out.print(date);
      out.write("</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"static/styles.css\">\r\n");
      out.write("    <style>\r\n");
      out.write("        .main {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            gap: 30px;\r\n");
      out.write("        }\r\n");
      out.write("        .container {\r\n");
      out.write("            width: 250px;\r\n");
      out.write("            height: 300px;\r\n");
      out.write("            overflow: auto;\r\n");
      out.write("            scrollbar-width: thin;\r\n");
      out.write("        }\r\n");
      out.write("        #Fixed {\r\n");
      out.write("            margin-top: -20px;\r\n");
      out.write("            margin-bottom: -15px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<nav>\r\n");
      out.write("    ");
 if (date.equals("Today")){
      out.write("\r\n");
      out.write("        <button id=\"Tomorrow\" onclick=\"window.location.href='/plan.html?date=Tomorrow';\">Tomorrow</button>\r\n");
      out.write("        <button id=\"Yesterday\" onclick=\"window.location.href='/plan.html?date=Yesterday';\">Yesterday</button>\r\n");
      out.write("    ");
 }else if(date.equals("Yesterday")){
      out.write("\r\n");
      out.write("        <button id= \"Today1\" onclick=\"window.location.href='/plan.html?date=Today';\">Today</button>\r\n");
      out.write("        <button id=\"Tomorrow\" onclick=\"window.location.href='/plan.html?date=Tomorrow';\">Tomorrow</button>\r\n");
      out.write("    ");
} else{ 
      out.write("\r\n");
      out.write("        <button id=\"Today\" onclick=\"window.location.href='/plan.html?date=Today';\">Today</button>\r\n");
      out.write("        <button id=\"Yesterday\" onclick=\"window.location.href='/plan.html?date=Yesterday';\">Yesterday</button>\r\n");
      out.write("    ");
} 
      out.write("\r\n");
      out.write("    <a href=\"search.html\">Search</a>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("<div class=\"main\">\r\n");
      out.write("    ");

        for (String key : sortedKeys) {
    
      out.write("\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <h2 id=\"Fixed\">");
      out.print( key );
      out.write("</h2>\r\n");
      out.write("\r\n");
      out.write("        <button id=\"all\" class = \"smallBTN\" onclick=\"window.location.href='/plan.html?date=");
      out.print(date);
      out.write("';\">All</button>\r\n");
      out.write("        <button id=\"");
      out.print(key);
      out.write("toDO\" class = \"smallBTN\" onclick=\"window.location.href='/sort.html?date=");
      out.print(date);
      out.write("&period=");
      out.print(key);
      out.write("&sortType=FALSE';\">📝</button>\r\n");
      out.write("        <button id=\"");
      out.print(key);
      out.write("completed\" class = \"smallBTN\" onclick=\"window.location.href='/sort.html?date=");
      out.print(date);
      out.write("&period=");
      out.print(key);
      out.write("&sortType=TRUE';\">✔</button>\r\n");
      out.write("        <button id=\"add\" class = \"smallBTN\" onclick=\"openModal('");
      out.print( key );
      out.write("')\">+</button>\r\n");
      out.write("\r\n");
      out.write("        ");

            for (List<String> activity : plan.get(key)) {
                String subject = activity.get(0);
                String time = activity.get(1);
                String note = activity.get(2);
                String complete = activity.get(3);
                String url = activity.get(4);
        
      out.write("\r\n");
      out.write("        <div class=\"subject-row\">\r\n");
      out.write("            <button\r\n");
      out.write("                    class=\"subject-name\"\r\n");
      out.write("                    onclick=\"openSUBJECT('");
      out.print( date );
      out.write("', '");
      out.print( key );
      out.write("', '");
      out.print( subject );
      out.write("', '");
      out.print( time );
      out.write("', '");
      out.print(note);
      out.write("', '");
      out.print(complete);
      out.write("', '");
      out.print(url);
      out.write("')\">\r\n");
      out.write("                ");
      out.print( subject );
      out.write("\r\n");
      out.write("            </button>\r\n");
      out.write("\r\n");
      out.write("            <form method=\"post\" action=\"edit.html\">\r\n");
      out.write("                <input type=\"hidden\"  name=\"oldDate\" value=\"");
      out.print(date);
      out.write("\">\r\n");
      out.write("                <input type=\"hidden\"  name=\"oldSubject\" value=\"");
      out.print(subject);
      out.write("\">\r\n");
      out.write("                <input type=\"hidden\"  name=\"oldPeriod\" value=\"");
      out.print(key);
      out.write("\">\r\n");
      out.write("                <input type=\"hidden\"  name=\"oldTime\" value=\"");
      out.print(time);
      out.write("\">\r\n");
      out.write("                <input type=\"hidden\"  name=\"oldNote\" value=\"");
      out.print(note);
      out.write("\">\r\n");
      out.write("                <input type=\"hidden\"  name=\"oldComplete\" value=\"");
      out.print(complete);
      out.write("\">\r\n");
      out.write("\r\n");
      out.write("                <input type=\"hidden\"  name=\"newDate\" value=\"");
      out.print(date);
      out.write("\">\r\n");
      out.write("                <input type=\"hidden\"  name=\"newSubject\" value=\"");
      out.print(subject);
      out.write("\">\r\n");
      out.write("                <input type=\"hidden\"  name=\"newPeriod\" value=\"");
      out.print(key);
      out.write("\">\r\n");
      out.write("                <input type=\"hidden\"  name=\"newTime\" value=\"");
      out.print(time);
      out.write("\">\r\n");
      out.write("                <input type=\"hidden\"  name=\"newNote\" value=\"");
      out.print(note);
      out.write("\">\r\n");
      out.write("                ");
  String value;
                    if (complete.equals("TRUE")) {
                        value = "FALSE";
                    }else{
                        value = "TRUE";
                    }
                
      out.write("\r\n");
      out.write("                <input type=\"hidden\"  name=\"newComplete\" value=\"");
      out.print(value);
      out.write("\">\r\n");
      out.write("\r\n");
      out.write("                ");
 if (complete.equals("FALSE")){
      out.write("\r\n");
      out.write("                    <button type = \"submit\" class=\"incomplete\">✔</button>\r\n");
      out.write("                ");
}else{
      out.write("\r\n");
      out.write("                    <button type = \"submit\" class=\"complete\">✔</button>\r\n");
      out.write("                ");
}
      out.write("\r\n");
      out.write("            </form>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("    ");
 } 
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div id=\"modal\" class=\"modal\">\r\n");
      out.write("    <div class=\"modal-content\">\r\n");
      out.write("        <span class=\"close\" onclick=\"closeModal()\">&times;</span>\r\n");
      out.write("        <h2>Add Activity to <span id=\"modal-title\"></span></h2>\r\n");
      out.write("\r\n");
      out.write("        <form action=\"/add.html\" method=\"post\">\r\n");
      out.write("            <label for=\"subject\">Subject:</label>\r\n");
      out.write("            <input type=\"text\" id=\"subject\" name=\"subject\" required><br><br>\r\n");
      out.write("\r\n");
      out.write("            <label for=\"time\">Time:</label>\r\n");
      out.write("            <input type=\"number\" step=\"any\" id=\"time\" name=\"time\" required><br><br>\r\n");
      out.write("\r\n");
      out.write("            <label for=\"note\">Note</label>\r\n");
      out.write("            <input type=\"text\" id=\"noteR\" name=\"note\" required><br><br>\r\n");
      out.write("\r\n");
      out.write("            <label for=\"image\">Image URL:</label>\r\n");
      out.write("            <input type=\"url\" name=\"url\"><br><br>\r\n");
      out.write("\r\n");
      out.write("            <input type=\"hidden\" id=\"period\" name=\"period\">\r\n");
      out.write("            <input type=\"hidden\" id=\"day\" name=\"day\" value=");
      out.print(date);
      out.write(">\r\n");
      out.write("\r\n");
      out.write("            <button type=\"submit\">Add</button>\r\n");
      out.write("        </form>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div id=\"modal2\" class=\"modal\">\r\n");
      out.write("    <div class=\"modal-content\">\r\n");
      out.write("        <span class=\"close\" onclick=\"closeModal()\">&times;</span>\r\n");
      out.write("        <h2><span id=\"data-period\"></span> of <span id=\"date\"></span></h2>\r\n");
      out.write("        <p id =\"disclaimer\"> (Click VIEW to view pictures)</p>\r\n");
      out.write("        <p> Subject: <span id=\"subjectName\"></span> </p>\r\n");
      out.write("        <p> Hours to Spend: <span id=\"subjectTime\"></span> </p>\r\n");
      out.write("        <p> Completed status: <span id=\"complete\"></span></p>\r\n");
      out.write("        <p>Note: <span id=\"note\"></span></p>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"button-container\">\r\n");
      out.write("            <form method=\"POST\" action=\"/delete.html\">\r\n");
      out.write("                <input type=\"hidden\" id=\"date1\" name=\"date\">\r\n");
      out.write("                <input type=\"hidden\" id=\"date-period1\" name=\"period\">\r\n");
      out.write("                <input type=\"hidden\" id=\"subjectName1\" name=\"subject\">\r\n");
      out.write("                <input type=\"hidden\" id=\"subjectTime1\" name=\"time\">\r\n");
      out.write("                <input type=\"hidden\" id=\"note1\" name=\"note\">\r\n");
      out.write("                <input type=\"hidden\" id=\"complete1\" name=\"complete\">\r\n");
      out.write("                <button class=\"submit\">🗑️</button>\r\n");
      out.write("            </form>\r\n");
      out.write("\r\n");
      out.write("            <button class=\"edit-btn\" onclick=\"openEditModal(\r\n");
      out.write("                document.getElementById('date').textContent,\r\n");
      out.write("                document.getElementById('data-period').textContent,\r\n");
      out.write("                document.getElementById('subjectName').textContent,\r\n");
      out.write("                document.getElementById('subjectTime').textContent,\r\n");
      out.write("                document.getElementById('note').textContent,\r\n");
      out.write("                document.getElementById('complete').textContent\r\n");
      out.write("            )\">✏️</button>\r\n");
      out.write("\r\n");
      out.write("            <form method=\"POST\" action=\"/display.html\">\r\n");
      out.write("                <input type=\"hidden\" id=\"date2\" name=\"date\">\r\n");
      out.write("                <input type=\"hidden\" id=\"date-period2\" name=\"period\">\r\n");
      out.write("                <input type=\"hidden\" id=\"subjectName2\" name=\"subject\">\r\n");
      out.write("                <input type=\"hidden\" id=\"subjectTime2\" name=\"time\">\r\n");
      out.write("                <input type=\"hidden\" id=\"note2\" name=\"note\">\r\n");
      out.write("                <input type=\"hidden\" id=\"complete2\" name=\"complete\">\r\n");
      out.write("                <input type=\"hidden\" id=\"url\" name=\"url\">\r\n");
      out.write("                <button class=\"submit\">VIEW</button>\r\n");
      out.write("            </form>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div id=\"editModal\" class=\"modal\">\r\n");
      out.write("    <div class=\"modal-content\">\r\n");
      out.write("        <span class=\"close\" onclick=\"closeModal()\">&times;</span>\r\n");
      out.write("\r\n");
      out.write("        <form action=\"/edit.html\" method=\"post\">\r\n");
      out.write("            <h2>Edit Activity for <span id=\"edit-modal-title\"></span></h2>\r\n");
      out.write("\r\n");
      out.write("            <input type=\"hidden\" id=\"old-date\" name=\"oldDate\">\r\n");
      out.write("            <input type=\"hidden\" id=\"old-subject\" name=\"oldSubject\">\r\n");
      out.write("            <input type=\"hidden\" id=\"old-period\" name=\"oldPeriod\">\r\n");
      out.write("            <input type=\"hidden\" id=\"old-time\" name=\"oldTime\">\r\n");
      out.write("            <input type=\"hidden\" id=\"old-note\" name=\"oldNote\">\r\n");
      out.write("            <input type=\"hidden\" id=\"old-complete\" name=\"oldComplete\">\r\n");
      out.write("\r\n");
      out.write("            <label for=\"new-subject\">Subject:</label>\r\n");
      out.write("            <input type=\"text\" id=\"new-subject\" name=\"newSubject\" required><br><br>\r\n");
      out.write("\r\n");
      out.write("            <label for=\"new-time\">Time:</label>\r\n");
      out.write("            <input type=\"number\" step=\"any\" id=\"new-time\" name=\"newTime\" required><br><br>\r\n");
      out.write("\r\n");
      out.write("            <label for=\"new-note\">Note:</label>\r\n");
      out.write("            <input type=\"text\" id=\"new-note\" name=\"newNote\" required><br><br>\r\n");
      out.write("\r\n");
      out.write("            <label for=\"image\">Image URL:</label>\r\n");
      out.write("            <input type=\"url\" id=\"image\" name=\"url\"><br><br>\r\n");
      out.write("\r\n");
      out.write("            <label for=\"new-complete\">Completed:</label>\r\n");
      out.write("            <select id=\"new-complete\" name=\"newComplete\">\r\n");
      out.write("                <option value=\"FALSE\">Not Completed</option>\r\n");
      out.write("                <option value=\"TRUE\">Completed</option>\r\n");
      out.write("            </select><br><br>\r\n");
      out.write("\r\n");
      out.write("            <input type=\"hidden\" id=\"new-period\" name=\"newPeriod\">\r\n");
      out.write("            <input type=\"hidden\" id=\"new-day\" name=\"newDate\">\r\n");
      out.write("\r\n");
      out.write("            <button type=\"submit\" id=\"save\">Save Changes</button>\r\n");
      out.write("        </form>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("    function openEditModal(date, period, subject, time, note, complete) {\r\n");
      out.write("        let modal = document.getElementById(\"editModal\");\r\n");
      out.write("\r\n");
      out.write("        document.getElementById(\"old-date\").value = date;\r\n");
      out.write("        document.getElementById(\"old-subject\").value = subject;\r\n");
      out.write("        document.getElementById(\"old-period\").value = period;\r\n");
      out.write("        document.getElementById(\"old-time\").value = time;\r\n");
      out.write("        document.getElementById(\"old-note\").value = note;\r\n");
      out.write("        document.getElementById(\"old-complete\").value = complete;\r\n");
      out.write("\r\n");
      out.write("        document.getElementById(\"edit-modal-title\").textContent = period;\r\n");
      out.write("        document.getElementById(\"new-subject\").value = subject;\r\n");
      out.write("        document.getElementById(\"new-time\").value = time;\r\n");
      out.write("        document.getElementById(\"new-note\").value = note;\r\n");
      out.write("        document.getElementById(\"new-complete\").value = complete;\r\n");
      out.write("        document.getElementById(\"new-period\").value = period;\r\n");
      out.write("        document.getElementById(\"new-day\").value = date;\r\n");
      out.write("\r\n");
      out.write("        modal.style.display = \"block\";\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    function openSUBJECT(date, period, subject, time, note, complete, url) {\r\n");
      out.write("        let modal = document.getElementById(\"modal2\");\r\n");
      out.write("\r\n");
      out.write("        document.getElementById(\"date\").textContent = date;\r\n");
      out.write("        document.getElementById(\"data-period\").textContent = period;\r\n");
      out.write("        document.getElementById(\"subjectName\").textContent = subject;\r\n");
      out.write("        document.getElementById(\"subjectTime\").textContent = time;\r\n");
      out.write("        document.getElementById(\"note\").textContent = note;\r\n");
      out.write("        document.getElementById(\"complete\").textContent = complete;\r\n");
      out.write("\r\n");
      out.write("        document.getElementById(\"date1\").value = date;\r\n");
      out.write("        document.getElementById(\"date-period1\").value = period;\r\n");
      out.write("        document.getElementById(\"subjectName1\").value = subject;\r\n");
      out.write("        document.getElementById(\"subjectTime1\").value = time;\r\n");
      out.write("        document.getElementById(\"note1\").value = note;\r\n");
      out.write("        document.getElementById(\"complete1\").value = complete;\r\n");
      out.write("\r\n");
      out.write("        document.getElementById(\"date2\").value = date;\r\n");
      out.write("        document.getElementById(\"date-period2\").value = period;\r\n");
      out.write("        document.getElementById(\"subjectName2\").value = subject;\r\n");
      out.write("        document.getElementById(\"subjectTime2\").value = time;\r\n");
      out.write("        document.getElementById(\"note2\").value = note;\r\n");
      out.write("        document.getElementById(\"complete2\").value = complete;\r\n");
      out.write("        document.getElementById(\"url\").value = url;\r\n");
      out.write("\r\n");
      out.write("        modal.style.display = \"block\";\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    function openModal(period) {\r\n");
      out.write("        document.getElementById('modal').style.display = 'block';\r\n");
      out.write("        document.getElementById('modal-title').textContent = period;\r\n");
      out.write("        document.getElementById('period').value = period;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    function closeModal() {\r\n");
      out.write("        document.getElementById(\"modal\").style.display = \"none\";\r\n");
      out.write("        document.getElementById(\"modal2\").style.display = \"none\";\r\n");
      out.write("        document.getElementById(\"editModal\").style.display = \"none\";\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    window.onclick = function(event) {\r\n");
      out.write("        let modal = document.getElementById(\"modal\");\r\n");
      out.write("        let modal2 = document.getElementById(\"modal2\");\r\n");
      out.write("        let editModal = document.getElementById(\"editModal\")\r\n");
      out.write("        if (event.target === modal) {\r\n");
      out.write("            modal.style.display = \"none\";\r\n");
      out.write("        }\r\n");
      out.write("        if (event.target === modal2) {\r\n");
      out.write("            modal2.style.display = \"none\";\r\n");
      out.write("        }\r\n");
      out.write("        if (event.target === editModal){\r\n");
      out.write("            editModal.style.display = \"none\";\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("    document.addEventListener(\"DOMContentLoaded\", function () {\r\n");
      out.write("        let buttons = document.querySelectorAll(\"#MORNINGtoDO, #MORNINGcompleted, \" +\r\n");
      out.write("            \"#AFTERNOONtoDO, #AFTERNOONcompleted, \" +\r\n");
      out.write("            \"#EVENINGtoDO, #EVENINGcompleted, #all, #add\", \"#save\");\r\n");
      out.write("\r\n");
      out.write("        // Retrieve the last active button from localStorage\r\n");
      out.write("        let activeButton = localStorage.getItem(\"activeButton\");\r\n");
      out.write("\r\n");
      out.write("        if (activeButton) {\r\n");
      out.write("            document.getElementById(activeButton)?.classList.add(\"active\");\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        buttons.forEach(button => {\r\n");
      out.write("            button.addEventListener(\"click\", function () {\r\n");
      out.write("                buttons.forEach(btn => btn.classList.remove(\"active\"));\r\n");
      out.write("\r\n");
      out.write("                if (this.id !== \"all\" && this.id !== \"add\" && this.id !== \"save\") {\r\n");
      out.write("                    this.classList.add(\"active\");\r\n");
      out.write("                    localStorage.setItem(\"activeButton\", this.id);\r\n");
      out.write("                } else {\r\n");
      out.write("                    localStorage.removeItem(\"activeButton\");\r\n");
      out.write("                }\r\n");
      out.write("            });\r\n");
      out.write("        });\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
